### PR TITLE
Update nucleus.css

### PR DESCRIPTION
**Pull request by tetsuotram**
this solve the issue #2979

### CODE REVIEW

**Comment by marktaylor46** [comment]
That's not actually a bug - it's a CSS hack for IE9. All other browser will ignore it.

**Comment by tetsuotram** [comment]
thank you Mark for the reply!
But I can see that my Firefox is throwing an error: do you mean that I can safely ignore it?

**Comment by marktaylor46** [comment]
Is it really an error or a warning? It's quite common for browser to issue warnings about things they don't understand - a warning you can ignore.

**Comment by tetsuotram** [comment]
yes it is a warning.
thank you: I was not aware of this kind of hack

**Comment by mahagr** [comment]
The line should really be removed as we have already dropped IE9 support.

**Pull request closed without merging**
