### PR TITLE
Update Platform.php

### PR DESCRIPTION
**Pull request by dazzyon**
Passes shortcode enabled particles through the translate function.

See issue #886

### CODE REVIEW

**Comment by w00fz** [comment]
@newkind @mahagr any reason why this hasn't been merged in yet? I can merge it in, just want to be sure there isn't anything else involved?

Unless there really isn't a reason to get this merged, I don't see why a PR like this should stay open for this long :)

**Comment by newkind** [comment]
Well I have doubts about it and I want to investigate it a little bit more. I don't think that we should use this translate function as it's an WP internal one and direct calling it should be avoided. I want to find better and more reliable solution firstly and use this if I won't find anything else.

**Comment by w00fz** [comment]
Roger that.

**Comment by w00fz** [comment]
Any progress on this one or should we close the PR?

**Comment by mahagr** [comment]
To be honest, I'm also not liking automatic translation during filtering -- whether to translate a text field or not should be decided by particle. Or just create/use shortcode mechanism to do that.

**Comment by newkind** [comment]
I agree with @mahagr. I think that we should figure out a proper solution for this ie. why it works with widgets and not particles, rather than pass all shortcodes through translate function as this can produce some unexpected results ie. common words like `gallery` could get auto-translated thus making the shortcodes broken.

Let's discuss this in original issue #886 

Closing.

**Pull request closed without merging**
