### PR TITLE
Boxed Width Option

### PR DESCRIPTION
**Pull request by gospelpowered**
Allows the user to enable boxed design and specify in rem or % the width of their site. It leaves the breakpoints setting to control the proximity to the boxed design wall. The user can then control both to a width they prefer.

Not 100% on the mediaqueries.

This is an alternative proposal to #301

### CODE REVIEW

**Comment by mahagr** [comment]
Competing solution with Pull Request #301

@kevlardev when you have some time, I'd like you to look into both.

**Comment by adi8i** [comment]
you have not forgotten anything?

**Comment by adi8i** [comment]
I am sorry, but i don't see how this code will works ?  
First of all `$base-width` is not assigned to any width, and there is `margin: 0 auto` for `#g-page-surround`, that id doesn't have any `margin` , `margins` are added to `g-container` .

Maybe i don't understand `@if` condition in `sass` is more like a question :)

**Comment by JoomFX** [comment]
@adi8i download both files and test it

`$base-width` is defined in [base.yaml](https://github.com/gospelpowered/gantry5-1/commit/5bf86a52892e44a5787a6ff26f5c57a1c8e0026b) and then the SCSS variable is used in [_core.scss](https://github.com/gospelpowered/gantry5-1/commit/48b987ff1cc150f7bdb4e7bbb9f845eeb3fa61aa). I haven't tested it tho but it should work.

As I told @gospelpowered , his solution seems to be more flexible and user-friendly than mine. The only thing I do not like is that there are quite some adjustments for the different resolutions, while in mine there is just a single class added to the `g-page-surround` element.

I really do not know which one is better. Both have pros and cons ;)

**Comment by adi8i** [comment]
oops didn't seen the width added for large display :laughing:

**Comment by mahagr** [comment]
Related to #434

**Pull request closed without merging**
