### PR TITLE
Update init.php

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
Fix plugin updates issue #1271

### CODE REVIEW

**Comment by mahagr** [comment]
The function is not only used for plugin, but also for gantry themes.

**Comment by Matt-Yorkley** [comment]
That's why it checks if $options['plugin'] is set first, then if it is set and $options['plugin'] is not "gantry5/gantry5.php", it returns...

**Comment by Matt-Yorkley** [comment]
The function in question is hooked into the Wordpress filter "upgrader_post_install", which gets called whenever plugins, themes or languages are updated or installed.

The data that gets passed to that function in the $options array as the second argument varies depending on what's being updated, sometimes $options['type'] is set as "plugin" or "theme", sometimes not, sometimes $option['theme'] or $options['plugin'] is set giving the path to the theme or plugin file. As the function gets called on _every_ plugin or theme update, it should have a check to see if the correct plugin is being updated and return if not.

If a plugin is being upgraded, the $options['plugin'] key will always be set (but not if it's a theme or language pack), and if gantry5 is being updated, the $options['plugin'] key will be "gantry5/gantry5.php".

Hence:
if(isset($options['plugin'] && $options['plugin'] != "gantry5/gantry5.php")) {
return;
}

**Comment by nikola3244** [comment]
@mahagr Are you sure that it is used for theme updates on WP? @w00fz said otherwise.
https://gitter.im/gantry/gantry5?at=57736a658c9263ba30253ff9

**Comment by w00fz** [comment]
I think matias meant it's future proof and currently check also theems even though we actually don't use nor check any themes on wordpress since we cannot put any theme in their repository.

**Comment by mahagr** [comment]
Actually it was a note to myself to fix an issue.

The purpose of the above code is to be able to allow user to easily install CI builds and even get back to previous version of Gantry. But the code doesn't do only that: it also allows theme updates to be manually installed instead of using FTP. This second part will fail after this change.

**Comment by nikola3244** [comment]
Yeah, I understand now what you guys mean.
Btw, I can give you a "broken" backup of my testing environment if it can
help with fixing the issue.

**Comment by mahagr** [comment]
The main issue while fixing issues in WP installer has been that we really cannot test the fixes on installer without making a release first. This issue is kind of easier to test, but again, we cannot really test if we break our updates instead.

Anyway, this will be fixed in few days if not today -- its something we cannot ignore.

**Comment by nikola3244** [comment]
Thank you Matias.
It is an important bug.

**Pull request merged**
