### PR TITLE
Taking the Layout from Admin

### PR DESCRIPTION
**Pull request by JoomFX**
Taking the option the user selects in the Admin, Styles tab, for Fullwidth or Boxed.

### CODE REVIEW

**Comment by mahagr** [comment]
Part of #287

**Comment by mahagr** [comment]
In the future I would rather see a single pull request on simple changes like this. Read Github documentation on how to clone your branch and how to do pull requests from your local branches. It should be easy and the docs in here are the best.

**Comment by JoomFX** [comment]
Thanks @mahagr :)

Just to comment on your suggestions - I had never used Github before the G5 project was released. Since then I'm reading the Github Documentation quite often. You can see my fork of G5 [here](https://github.com/JoomFX/gantry5) . 
I'm now using Sourcetree so I'm doing the Pull Requests at once, for example [this one](https://github.com/gantry/gantry5/pull/294) ;)

**Comment by mahagr** [comment]
@JoomFX We all needed to learn how to work with Github, but I can say you this: once you get it, you will never want to use anything else!

**Comment by JoomFX** [comment]
"*once you get it, you will never want to use anything else!*" - couldn't agree more. I'm already loving it, even though it is still confusing from time to time ;)

**Comment by mahagr** [comment]
The hardest thing in git is to understand that it is a distributed system and not centralized. So you need to be always thinking where you do the change: your local repo / your fork in github / upstream / something else.

**Comment by w00fz** [comment]
Part of #287 and now consolidated in #301

**Pull request closed without merging**
