### PR TITLE
File problem

### PR DESCRIPTION
**Pull request by vitorvfmf**
Hi, I am using this software for a while I want to thank you for it.

I just got a problem this month. When I tried to install the theme in wordpress I got an error saying that was not possible to unzip. 

I'm not sure what the problem is, but there is something about that zip file that WordPress doesn't like. I downloaded the wordpress-tpl_g5_hydrogen_v5.4.18.zip file to my local computer and examined it - it seems perfectly normal, but I get the same error you reported when I upload it into a new WordPress. I then extracted the g5_hydrogen directory from the zip file and compressed it into a new zip file. I was then able to upload the theme without error. The same happened with 5.4.19 version.

### CODE REVIEW

**Comment by mahagr** [comment]
Fixed in develop. In the future, please do not create pull requests for releases :)

**Comment by vitorvfmf** [comment]
I don't know how to use git to sent you information.
I was trying to help your project.

Em 3 de nov de 2017 6:43 AM, "Matias Griese" <notifications@github.com>
escreveu:

**Comment by mahagr** [comment]
You could just have sent link, no need to do pull request for that :)

**Comment by vitorvfmf** [comment]
But where I send the link?

Em 3 de nov de 2017 9:27 AM, "Matias Griese" <notifications@github.com>
escreveu:

**Pull request closed without merging**
