### PR TITLE
Update _core.scss

### PR DESCRIPTION
**Pull request by adi8i**

### CODE REVIEW

**Comment by mahagr** [comment]
@adi8i Can you explain a bit what you're trying to fix here. Forcing !important doesn't sound nice thing to do and shouldn't be used unless there is high demand on doing it.

**Comment by adi8i** [comment]
@mahagr `.btn-primary` doesn't override default joomla colors, need to be forced. Even if there is `background: $accent-color-1` , still joomla default (blue one) will be used.

**Comment by mahagr** [comment]
Thanks for the explanation, now it's just up to @kevlardev to decide if the change is something he wants to get in. :)

**Comment by kevlardev** [comment]
This is actually an issue thats come up do to some improper ordering of the theme's platform specific styling loading before bootstrap. We will fix this in a different way as it applies not only to the btn-primary but also several other elements.

**Comment by mahagr** [comment]
Fixed in #416

**Pull request closed without merging**
