### PR TITLE
New selectize field that list all pages / posts...

### PR DESCRIPTION
**Pull request by adi8i**
Example:

wp:
  type: wordpress.posts 
  label: Pages
  post_type: page

### CODE REVIEW

**Comment by w00fz** [comment]
Nice!

**Comment by w00fz** [comment]
Maybe those other settings can be dynamic as well?

```
'post_status':'publish',
'nopaging':'true',
'orderby':'title',
'order':'asc',
```

**Comment by adi8i** [comment]
Ok, sure.

**Comment by adi8i** [comment]
I changed `nopaging` with `post_per_page` too, if it's dynamic :)

**Comment by newkind** [comment]
I agree! Nice ;)

**Comment by w00fz** [comment]
Sweet, if you ( @adi8i @mahagr @newkind )  don't have anything else to add to this, we can merge it right away :+1:

**Comment by mahagr** [comment]
I'm fine to merge it.

**Comment by newkind** [comment]
I've merged it - thanks @adi8i !

**Comment by chaladm** [comment]
Noticed this was added to the version. How does an end user use this when building particles?

**Comment by newkind** [comment]
You need to set field type to be `type: wordpress.posts` It should render a dropdown in the admin with all posts inside of it.

**Pull request merged**
