### PR TITLE
To Top particle minor adjustments

### PR DESCRIPTION
**Pull request by adi8i**
This PR add a font awesome icon picker. I know you can add html in text field, but with this pr you can chose fa icons faster, also the particle have 3 fields so it's not overloaded.

### CODE REVIEW

**Comment by mahagr** [comment]
@kevlardev @w00fz what do you guys think?

**Comment by w00fz** [comment]
I guess it's ok but obviously like for any other Particle, you can kind of mix and match as you please so a lot of this should be kept simple and the enduser/developer should override the particle to accomplish what they desire.

I'm ok with this addition though, if you can make a few changes. Right now you have it set to have either the Icon or the Text, I'd like to have some logic so that you can end up with any combination:

 1. Icon only (Icon is set, Text is left empty)
 2. Text only (Text is set, Icon is left empty)
 3. Both Icon and Text (both Icon and Text are set)

**Comment by adi8i** [comment]
I can't think of a way to do that, because of this `{{particle.content|default('To Top')|raw}}`, if i'll remove default value, by default the particle will show an empty space and that's not fine.

**Comment by mahagr** [comment]
You can keep the default value, but wrap the content into {% if }

**Comment by mahagr** [comment]
Or better, use something like this:

    {% set content = particle.content ?: (particle.icon ? '' : 'To Top') %}

And use the new variable.

Basically what this does is to use particle.content if it is set, otherwise use default text only if icon isn't there.

**Comment by mahagr** [comment]
Changelog entry is missing!

**Comment by w00fz** [comment]
I'm writing it

**Pull request merged**
