### PR TITLE
Menu Item Link Target Extension - Firefox Tab Pinning Adaption

### PR DESCRIPTION
**Pull request by thexmanxyz**
Hey there, first of all I hope this Pull Request doesn't create a mess. If so I will cancel it and try something else but I already did a mistake as I didn't create a branch for my last PR which is still open.

So I had to create a branch from my fork based on the last commit before I commited to my fork to don't mess up commits in the second pull request. However from the preview it seems to work as expected ;).

Please take further information concerning this Pull Request from Issue #2273. I added another option to the menu item configuration which allows us to force the `target` attribute for menu links e.g. this is relevant for the target option `_self` were currently no `target` will be rendered to the DOM.

<del>But basically the changes add another option to the link target dropdown of menu items. This means the user can differentiate between:</del>

- <del>**none:** no target attribute will be rendered for the menu item link</del>
- <del>**self:** the target will be rendered as `target="_self"`</del>

This modification is not absolutely necessary but Firefox has a "bug" (it's not clear if it will be ever fixed) which breaks the target behaviour for pinned tabs if the target attribute hasn't been specified. Hence, FF forces tabs to be opened as they were attributed with `_blank` even thought there is no `target` attribute defined on that link. This modification gives users the option to shift around this issue by forcing `target="_self"` on menu links. The default behaviour is preserved => no target attribute is rendered.

Info: Please take also a look to the deleted stuff above. I reworked the PR because it's not possible to add another option to the Gantry menu target setting since it is connected with the Joomla menu target setting. Therefore I added the 'Force Target' checkbox instead.

### CODE REVIEW

**Comment by mahagr** [comment]
@thexmanxyz What if we move this fix into the menu parameters instead of forcing people to enable this option for every single menu item?

**Comment by mahagr** [comment]
Fixed in ab7081d

**Comment by thexmanxyz** [comment]
@mahagr Thanks for fixing the issue and mentioning. I think the menu parameter option is the better fix!

**Comment by thexmanxyz** [comment]
@mahagr Please also check my comment on https://github.com/gantry/gantry5/commit/ab7081d0e77bcd45e21295d6d5c584fcc86df5db. Don't want to open another PR just for this tiny change.

**Pull request closed without merging**
