### PR TITLE
Enhance Copyright particle to include html

### PR DESCRIPTION
**Pull request by topwebs**
#906

### CODE REVIEW

**Comment by JoomFX** [comment]
Either chage:

```
{{ (particle.filter ? gantry.platform.filter(particle.owner) : particle.owner)|html|raw }}
```

To this:

```
{{ gantry.platform.filter(particle.owner)|html|raw }}
```

Or add the filter option to the "Copyright" particle YAML file.

```
    filter:
      type: input.checkbox
      label: Process shortcodes
      description: Enable shortcode processing / filtering in the content.
```

**Comment by topwebs** [comment]
OK, I've added the filter. So, now the Copyright particle is basically the same as the Custom HTML particle.

**Comment by JoomFX** [comment]
Yep, with the nice code for the copyright years that you want :)

**Comment by mahagr** [comment]
I have troubles of including this change as it breaks existing sites on escaping `&` into `&amp;` which is highly likely string used in copyright text, potentially breaking html in thousands of existing sites.

Maybe add option "Enable HTML" with description off "WARNING: If you enable this feature, you need to escape characters like & => &amp;" and disable HTML by default.

**Comment by w00fz** [comment]
I don't really like this change. 
Filter is quite an expensive method to call (especially in Joomla). It does make sense to have it in the Custom HTML particle, where things can go wild, however in the Copyright particle, the field is controlled and all you will ever do is either link the owner or add some inline tags such as `strong` or `em`.

I think it should just be served as `|raw` to allow you to add the link you were asking, or any other HTML for what matters, but the extra options and filtering, that I feel like it shouldn't be part of Gantry, eventually one could override or create their own Copyright particle, if that's the desired behavior.

This PR should be reverting the `yaml` and `twig`. The `twig` then should just change `{{ particle.owner|e }}` to `{{ particle.owner|raw }}`.

**Comment by topwebs** [comment]
OK. Changed pull request per @w00fz to serve `|raw` in Copyright particle.

**Comment by w00fz** [comment]
Thank you @topwebs !

**Comment by mahagr** [comment]
My concern with copyrights like `Me & You` is still there. Without escaping we break all the existing sites using & in the copyright.

**Pull request merged**
