### PR TITLE
Joomla: Give G5 framework the ability to accept extra body classes

### PR DESCRIPTION
**Pull request by joomlabeat**
#2166 

This PR - opens up a window for additional customization by other Joomla devs. Gantry framework will check for a special reserved array variable in JInput - devs can use a custom plugin to assign elements on an array and then set that variable to JInput - If Gantry finds this variable, it will loop over the elements and assign those as additional classes to the document body.

This is just a minimum addition for those that are looking for this extra customization ability.

### CODE REVIEW

**Comment by mahagr** [comment]
I'm not really happy with this kind of solution as IMHO it allows end users to customize the site without site owners approval.

**Comment by joomlabeat** [comment]
@mahagr 
hey there... I agree with you on the first part that is: I am not really happy with this solution. My reasons though are different: 

It feels a bit "hacky" and it's not that elegant
It would require additional Joomla coding for someone to add custom classes to the body
it's not actual part of gantry that can be managed from the gantry admin (this last one sounds similar to what you said).

At the other side:
It's easy and simple implementation for gantry. 
It can be useful for template and other devs that need to overcome that small gantry's limitation, as it opens up that small window.  
It could be a small hidden feature inside gantry, till a more elegant or complete solution comes out. 

Having said that - I am still not sure what I decisions I would make, if I was the gantry framework developer.

*I already use it on one website with a custom gantry template. I will be ok to maintain this on my own after any Gantry updates.

**Comment by mahagr** [comment]
Maybe an event to hook into instead of this, one that allows you to add body classes from a plugin. Would that solve your issues?

And no, I don't think I want to implement this in this way... :cry:

**Comment by joomlabeat** [comment]
I started digging for a better way, but various life events distrusted me from anything work related. I am trying to catchup with my work at the moment. 
I will get back to this at a later time.

**Comment by mahagr** [comment]
This pull request has no changed code. Closing.

**Pull request closed without merging**
