### PR TITLE
Patch 2

### PR DESCRIPTION
**Pull request by adi8i**
Minor adjustments to logo particle

### CODE REVIEW

**Comment by mahagr** [comment]
Not sure if this is the best way to do it as the text kind of needs to be there (do we want to allow empty value on it)?

**Comment by adi8i** [comment]
Hm, then i understood this wrong, it picks the default value from yaml file. But that field can be saved empty, i think this is what you mean.

**Comment by mahagr** [comment]
Well, it's not that I was denying the request; I just wanted to know if the new behavior was what we wanted or not. :)

**Comment by w00fz** [comment]
There isn't a reason for the logo particle to be used if you aren't picking any image nor any  text. So I think the current behavior is the right one. In the PR it's cleaner since we can now use blueprints' default.

Also Adrian, your other change to the url() is a good catch, although you have a typo, you need to remove that extra closing parenthesis at the end, after image.

// Djamil Legato // From iPhone //

**Comment by mahagr** [comment]
If we want no logo to show up, I would just return no content to free up the place particle is taking. In this code you could have empty text, no image and it still contains link.

**Pull request closed without merging**
