### PR TITLE
XML file update server referenced does not

### PR DESCRIPTION
**Pull request by webmasterab**
XML file update server referenced does not

### CODE REVIEW

**Comment by mahagr** [comment]
Seems to work just fine for me. I'm closing this one as this is a pull request and I don't accidentally want to merge it.

**Comment by webmasterab** [comment]
Good morning,
In my screenshot you can see how the XML looks at me.
Therefore, he does not
It is not an XML structure.

That's what I wanted to report and therefore I do not mention the update

Hope you can fiddle
And want to help me

Sincerely,
A. Booij

[cid:image001.png@01D2B441.A2753570]

Met vriendelijke groet,

Arjan Booij

Van: Matias Griese [mailto:notifications@github.com]
Verzonden: maandag 10 april 2017 08:27
Aan: gantry/gantry5 <gantry5@noreply.github.com>
CC: webmasterab <abooij@live.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [gantry/gantry5] XML file update server referenced does not (#1959)


Seems to work just fine for me. I'm closing this one as this is a pull request and I don't accidentally want to merge it.

**Comment by mahagr** [comment]
@webmasterab Your image doesn't show up, please use github website to add it.

**Comment by webmasterab** [comment]
If I visit this url from update management
http://updates.gantry.org/5.0/joomla/pkg_gantry5.xml
Then I get this into the picture as text, and that is wrong according to me, so I get the update messages are not

pkg_gantry5 Gantry Framework package pkg_gantry5 5.4.11 http://docs.gantry.org/gantry5 http://updates.gantry.org/download/5.4.11/joomla-pkg_gantry5_v5.4.11.zip stable RocketTheme, LLC http: // gantry.org
updates
site

In this http://updates.gantry.org/5.0/joomla/tpl_g5_hydrogen.xml

g5_hydrogen Hydrogen Template g5_hydrogen template 5.4.11 http://docs.gantry.org/gantry5 http://updates.gantry.org/download/5.4.11/joomla-tpl_g5_hydrogen_v5.4.11.zip stable Rockettheme, LLC http: // gantry.org
updates
site

This is what I had shown in the image.
The XML format is different from other update sites

Hope you can do something with it or I keep an eye on the needs updates.
But the best is that you get a message

**Comment by mahagr** [comment]
To me the XML looks good -- please see the source code instead of the rendered output by the browser (it thinks it is html).

**Pull request closed without merging**
