### PR TITLE
Removing Title Links from Joomla Article Particle #2820

### PR DESCRIPTION
**Pull request by dmleeman**
Joomla 3.9.27
PHP 7.4.16
Gantry 5.4.37

I'm having some problem with Joomla and Gantry5 Joomla Articles particle. I have set up Modules in which the Joomla Article particle sits. Each Article has its own title and this is shown as the title of the article in the module/particle combo.
The problem is that I cannot remove the link from the article title, even through use of Joomla globals. So, all articles try to open on the home page as itemID101 from the link inherent in the title.
Has anyone come across this?
I am only using the default Joomla Articles particle that comes with base Gantry5

image

### CODE REVIEW

**Comment by mahagr** [comment]
There's something wrong with your pull request. Can you please change the target branch to `feature/v5.5.0` instead of `develop`?

**Comment by mahagr** [comment]
Actually.. I don't think this has your changes at all.

**Comment by dmleeman** [comment]
Yup, I'm in the wrong branch! Will figure this out carefully so I don't mess up again.

**Comment by mahagr** [comment]
Just create a new pull request with the correct branches. I'm closing this one.

**Pull request closed without merging**
