### PR TITLE
Italy Cookie Law

### PR DESCRIPTION
**Pull request by mariantanase**
With the new Cookie Law in Italy, anonymize google analytics is mandatory.

### CODE REVIEW

**Comment by mahagr** [comment]
Might be EU wide law... Can someone check it out?

**Comment by w00fz** [comment]
Yes this is a EU legislation on cookies. @mariantanase if you can edit your pull request to change `(mandatory in Germany and Italy)` with just `(mandatory in Europe)` I can just merge your PR.

**Comment by mariantanase** [comment]
Ok. Can you check if now is correct ?

**Comment by w00fz** [comment]
Yup looking perfect. Thank you!

**Pull request merged**
