### PR TITLE
Small fix. Flex should be `0 value`.

### PR DESCRIPTION
**Pull request by adi8i**

### CODE REVIEW

**Comment by mahagr** [comment]
Shrink, not grow. Makes sense.

**Comment by adi8i** [comment]
Sorry for insist on an issue that's not important.  Looks like the code was not compiled.

**Comment by mahagr** [comment]
@w00fz Can you recompile nucleus CSS? I have some issues with the generated CSS.

**Comment by newkind** [comment]
Recompiled ;)

**Pull request merged**
