### PR TITLE
Added FA5 frontend support, Added FA version load routine

### PR DESCRIPTION
**Pull request by thexmanxyz**
Hey folks, I finally decided to update the Gantry frontend to fully support Font Awesome 5 (like requested in #2196). Hence I improved / extended the with #2540 introduced settings panel within the `Page Settings`. Please also review the screenshots I attached below to get a feeling on how the new functionality works.

The updated panel now has the following settings:
- `Version` - the version of the Font Awesome library that should be loaded
  - `Font Awesome 4` - legacy support with the old v4 library
  - `Font Awesome 5 (SVG)` - JS library based on SVG
  - `Font Awesome 5 (Webfont)` - CSS library with Webfont
  - `Manual` - gives the user the opportunity to manually define imports (e.g. CDN, or new versions)
  - `Disable` - completely disables the Font Awesome loading routine
- `V4 Compatibility` - loads the Font Awesome 4 shim (only necessary for FA5)
- `Content Compatibility` - more on that later, but basically this loads a custom created shim CSS file which allows to use FA symbols in the CSS `content` rule - so called [pseudo-elements](https://fontawesome.com/how-to-use/on-the-web/advanced/css-pseudo-elements). This was necessary to provide support for these elements when choosing `Font Awesome 5 (SVG)` as Gantry makes use of them at certain places and FA5 (SVG) does not have a good native support for these elements.
- `HTML CSS Import` - add custom HTML to import library via `<link>` and CSS
- `HTML JS Import` - add custom HTML to import library via `<script>` and JS

The import differentiation was made to separate the import routines within the file `page_head.html.twig`. This can also be achieved in one text area but I decided to keep things clean as originally intended.

I added the latest version (5.11.2) of FA5 [available here](https://fontawesome.com/how-to-use/on-the-web/setup/hosting-font-awesome-yourself). I will also attach the used package.

**Content Compatibility**
To guarantee that Font Awesome 5 (SVG) will work with pseudo-elements which are used within Gantry at certain places I created a new CSS file (`font-awesome5-pseudo.min.css`) which acts as some kind of shim to support these elements within Gantry. There is [a method](https://fontawesome.com/how-to-use/on-the-web/advanced/css-pseudo-elements#with-svg-js) to support pseudo-elements by Font Awesome (for SVG + JS) itself but I would not recommend using that as it is terrible slow and we are not able to attach the attribute `data-search-pseudo-elements` to `<script>` tags because of platform limitations. Here is the CSS I took directly from the FA5 CSS library to support pseudo-elements together with the SVG version of the library:

```CSS
@font-face {
  font-family: 'Font Awesome 5 Free';
  font-style: normal;
  font-weight: 400;
  font-display: auto;
  src: url("../webfonts/fa-regular-400.eot");
  src: url("../webfonts/fa-regular-400.eot?#iefix") format("embedded-opentype"), url("../webfonts/fa-regular-400.woff2") format("woff2"), url("../webfonts/fa-regular-400.woff") format("woff"), url("../webfonts/fa-regular-400.ttf") format("truetype"), url("../webfonts/fa-regular-400.svg#fontawesome") format("svg"); }

@font-face {
  font-family: 'Font Awesome 5 Free';
  font-style: normal;
  font-weight: 900;
  font-display: auto;
  src: url("../webfonts/fa-solid-900.eot");
  src: url("../webfonts/fa-solid-900.eot?#iefix") format("embedded-opentype"), url("../webfonts/fa-solid-900.woff2") format("woff2"), url("../webfonts/fa-solid-900.woff") format("woff"), url("../webfonts/fa-solid-900.ttf") format("truetype"), url("../webfonts/fa-solid-900.svg#fontawesome") format("svg"); }
```

Granted, we could skip the SVG + JS support completely or completely port Gantry to the SVG version but for the moment the solution I choose serves the purpose quite well (I guess). It might also be necessary to extend this shim CSS file or tweak it a little bit but just let me know what you think on that approach.

Finally I updated the `font-family` rules (where necessary) to support pseudo-elements in Gantry together with FA5. So I changed every occurrence of:

```CSS
  font-family: FontAwesome;
```

to 

```CSS
  font-family: FontAwesome, "Font Awesome 5 Free";
  font-weight: 900;
```

Hope this explanation helps to understand what this PR does and what was done so that we get this thing merged into core without delays. @newkind @yellowwebmonkey @mahagr @w00fz @n8solutions

**Version Selection**
grafik

**Font Awesome Panel**
grafik

**Font Awesome Library 5.11.2**
[fontawesome-free-5.11.2-web.zip](https://github.com/gantry/gantry5/files/3720671/fontawesome-free-5.11.2-web.zip)

### CODE REVIEW

**Comment by thexmanxyz** [comment]
@marktaylor46 @pplopx @810 @wbarnes @XaRz @adoewa @webhelpus @paolavness @Legolasindar @AndiLeni @Shorece @muffindcc Tagging people who either requested this feature or might have some useful input to contribute!

**Comment by N8Solutions** [comment]
@thexmanxyz Thank you very much for putting this pull request together!

Quick question, for those of us with FA5 Pro licenses, how does your pull request handle that?

You mentioned above that you changed

```
font-family: FontAwesome;
```
to
```
font-family: FontAwesome, "Font Awesome 5 Free";
font-weight: 900;
```
Have you taken in to consideration about supporting the other Font Awesome 5 `font-family`'s which includes the Pro users? Altogether, including the free version, there are 5 types, Solid, Regular, Light, Duotone, Brands, but only 4 different Font Awesome 5 `font-family`'s that can be used.
[https://fontawesome.com/how-to-use/on-the-web/advanced/css-pseudo-elements](https://fontawesome.com/how-to-use/on-the-web/advanced/css-pseudo-elements)

image

**Comment by thexmanxyz** [comment]
@N8Solutions You are very welcome.

I think there is a misconception on the pseudo-elements and `font-family`. Within Gantry we only have to support the `Solid` style because we just need it for pseudo-elements defined within the template / framework on CSS level. If you load your Pro version manually you have pseudo-element support for the 5 styles listed in the table. Basically we just have to ensure that pseudo-elements defined within the Gantry and template CSS are rendered correctly after switching version. So we just have to modify these CSS rules.

The only question is if the `Font Awesome 5 Free` `font-family` does work with a Pro license import. I'm not sure if this is the case. If not I have to tweak the PR a little bit. Actually just should not use pseudo-elements if you can prevent it. Everything is supported if you load the Pro version manually. If you need to tweak the pseudo-elements included with Gantry you have to override the CSS including them manually.

**Comment by mahagr** [comment]
Also make sure that we're forward compatible with Joomla 4 as it also uses FA5 AFAIK.

**Comment by pplopx** [comment]
Wow! Sounds great. Is he in the core yet? I can't wait to try it for feedback. Thanks!

**Comment by mahagr** [comment]
@thexmanxyz I've merged this with minor changes (B/C etc) to Gantry 5.5 branch. 

Is there anything special needed if we update the fonts to the latest version? I don't think so, but just in case...

**Comment by thexmanxyz** [comment]
@mahagr Sorry for not pushing this PR more forward. I'm happy to hear that we get the FA5 support merged :-). What does B/C stand for? Sorry für the dumb question.

Yes there is one more thing I did not consider in this PR as we still need the Pro support added. I suggest it's best that you simply search for the places and add the respective `font-family` entry where it is necessary to prevent overhead adding additional changes to this PR. So basically every occurence of

```CSS
font-family: FontAwesome, "Font Awesome 5 Free";
```

has to be replaced by

```CSS
font-family: FontAwesome, "Font Awesome 5 Free", Font Awesome 5 Pro;`
```

but I did not test if this work. I assume this should be the way to guarantee support for Pro integration as well.

**Comment by thexmanxyz** [comment]
@mahagr something like 40a3813 should serve the purpose, I might overlooked something but that's the places I added the `Font Awesome 5 Free`.

**Comment by mahagr** [comment]
I'm wondering if the ordering should be the opposite. Pro, Free, FA4? So if someone mistakenly loads more than one version, it would be using the best version, not the worst.

**Comment by thexmanxyz** [comment]
@mahagr I'm pretty sure that the ordering should be the opposite and exactly for the reason you wrote. This is a good input. Pro, Free, FA4 should be the actual ordering. I have to bother you again, what does B/C mean? :-D

**Comment by mahagr** [comment]
Merged to G5.5

**Comment by thexmanxyz** [comment]
@mahagr Thanks!

**Pull request closed without merging**
