### PR TITLE
Initial works for #1161

### PR DESCRIPTION
**Pull request by JoomFX**
Preparing `page.html.twig` for https://github.com/gantry/gantry5/issues/1161

What should we replace `{# PLACEHOLDER HERE #}` with?

--------

Sorry guys, I guess this PR is not much of a help :disappointed: 
Feel free to just reject it.
I wanted to implement the feature on my own but I guess I still need to learn a lot.

Basically, we just need to replace `{# PLACEHOLDER HERE #}` with something but I cannot figure it out.

### CODE REVIEW

**Comment by mahagr** [comment]
Looks good this far and shouldn't really break anything either.

The issue here is that it's really that simple to implement the feature; you would need to do similar stuff that I did for assets. Basically you need to grab twig output from the template and store that into an array until you grab it from there and insert back into the page.

The reason why I haven't already implemented this is that it takes probably a few hours to implement and test the feature.

**Comment by JoomFX** [comment]
I tested it and it works just fine so far... I mean there's no reason not to work since I'm just re-organizing the code, I'm not implementing anything :smile: 

Yes, I tried to implemented the feature by looking into the `assets` and the way you did it. But as soon as I saw the code in `TokenParserAssets.php` I just gave up... this stuff is not for a simple front-end developer :smile: 

I'll just wait for you to implement it, I guess...

And thanks :wink:

**Comment by mahagr** [comment]
Yeah, it was a pain to implement in the first place... But the new code should be somewhat easier as we already have similar classes and functions implemented.

**Comment by JoomFX** [comment]
Great! I hope it will be easier :wink:

**Comment by w00fz** [comment]
Is this getting followed up in a different way? Does the PR need to stay open still? 
Just wondering as we have a bunch of PR stale for a while and I'd like to close the unneeded ones 😄

**Comment by JoomFX** [comment]
@w00fz Hey Djamil,

No, this PR does not need to stay open. There's nothing valueable in it :smile: 

I'm waiting for Matias to implement this feature when he finds some free time... I guess it will be after the Grav implementation.

I haven't said it recently, so thanks a lot for all your hard work guys, it is really much appreciated ;)

**Comment by mahagr** [comment]
I'd vote to close one or the another, no need to have both pull request and an issue for the same thing. 

Will keep the issue open and close this one.

**Pull request closed without merging**
